from __future__ import annotations

from pathlib import Path

import numpy as np

from fascat.asset import Asset, Node, Part
from fascat.material import Material
from fascat.mesh import Mesh
from fascat.options import ObjExportOptions

OBJ_SUFFIXES = {".obj"}


def write_obj(asset: Asset, path: str | Path, *, options: ObjExportOptions | None = None) -> None:
    opts = options or ObjExportOptions()
    output_path = Path(path)
    if output_path.suffix.lower() not in OBJ_SUFFIXES:
        raise ValueError(f"unsupported OBJ extension: {output_path.suffix or '<none>'}")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = ["# Generated by fascat"]
    if opts.materials and opts.write_mtl and asset.materials:
        lines.append(f"mtllib {output_path.with_suffix('.mtl').name}")
    vertex_offset = 1
    for occurrence in _occurrences(asset):
        part = asset.parts.get(occurrence.part_id)
        if part is None or part.mesh is None:
            continue
        mesh = part.mesh
        name = _obj_name(occurrence.node.name or part.name or part.id)
        if opts.preserve_groups:
            lines.append(f"g {name}")
            lines.append(f"o {name}")
        points = _transform_points(mesh.points, occurrence.world_transform)
        for point in points:
            lines.append(f"v {point[0]:.9g} {point[1]:.9g} {point[2]:.9g}")
        current_material: str | None = None
        for face_index, face in enumerate(mesh.faces.astype(int).tolist()):
            material_id = _face_material_id(part, mesh, face_index)
            if opts.materials and material_id is not None and material_id != current_material:
                lines.append(f"usemtl {_obj_name(material_id)}")
                current_material = material_id
            a, b, c = (index + vertex_offset for index in face)
            lines.append(f"f {a} {b} {c}")
        vertex_offset += mesh.vertex_count

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if opts.materials and opts.write_mtl and asset.materials:
        _write_mtl(output_path.with_suffix(".mtl"), asset.materials)


def validate_obj(path: str | Path) -> dict[str, int]:
    text = Path(path).read_text(encoding="utf-8")
    vertices = sum(1 for line in text.splitlines() if line.startswith("v "))
    triangles = sum(1 for line in text.splitlines() if line.startswith("f "))
    if vertices == 0 or triangles == 0:
        raise RuntimeError("OBJ asset contains no mesh faces")
    return {"meshes": 1, "points": vertices, "triangles": triangles}


class _Occurrence:
    def __init__(self, node: Node, part_id: str, world_transform: np.ndarray) -> None:
        self.node = node
        self.part_id = part_id
        self.world_transform = world_transform


def _occurrences(asset: Asset) -> list[_Occurrence]:
    occurrences: list[_Occurrence] = []

    def walk(node: Node, world: np.ndarray) -> None:
        current = world @ node.transform
        if node.part_id is not None:
            occurrences.append(_Occurrence(node, node.part_id, current))
        for child in node.children:
            walk(child, current)

    walk(asset.root, np.eye(4, dtype=np.float64))
    return occurrences


def _transform_points(points: np.ndarray, transform: np.ndarray) -> np.ndarray:
    homogeneous = np.column_stack([points, np.ones(points.shape[0], dtype=np.float64)])
    return np.asarray((transform @ homogeneous.T).T[:, :3], dtype=np.float64)


def _face_material_id(part: Part, mesh: Mesh, face_index: int) -> str | None:
    if not part.material_ids:
        return None
    if mesh.material_indices is None:
        return part.material_ids[0]
    material_index = int(mesh.material_indices[face_index])
    return part.material_ids[material_index] if material_index < len(part.material_ids) else None


def _write_mtl(path: Path, materials: dict[str, Material]) -> None:
    lines: list[str] = ["# Generated by fascat"]
    for material in materials.values():
        lines.append(f"newmtl {_obj_name(material.id)}")
        lines.append(f"Kd {material.base_color[0]:.9g} {material.base_color[1]:.9g} {material.base_color[2]:.9g}")
        lines.append(f"d {material.opacity:.9g}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _obj_name(value: str) -> str:
    return "".join(character if character.isalnum() or character in {"_", "-", "."} else "_" for character in value)
