from __future__ import annotations

from io import StringIO
from pathlib import Path

import numpy as np

from fascat.asset import Asset, Node, Part
from fascat.export_report import referenced_materials
from fascat.material import Material
from fascat.mesh import Mesh
from fascat.options import ObjExportOptions

OBJ_SUFFIXES = {".obj"}


def write_obj(asset: Asset, path: str | Path, *, options: ObjExportOptions | None = None) -> None:
    _write_obj(asset, path, options=options, collect_stats=False)


def write_obj_with_validation_stats(
    asset: Asset,
    path: str | Path,
    *,
    options: ObjExportOptions | None = None,
) -> dict[str, int] | None:
    return _write_obj(asset, path, options=options, collect_stats=True)


def _write_obj(
    asset: Asset,
    path: str | Path,
    *,
    options: ObjExportOptions | None,
    collect_stats: bool,
) -> dict[str, int] | None:
    opts = options or ObjExportOptions()
    output_path = Path(path)
    if output_path.suffix.lower() not in OBJ_SUFFIXES:
        raise ValueError(f"unsupported OBJ extension: {output_path.suffix or '<none>'}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    written_materials = referenced_materials(asset)

    chunks: list[str] = ["# Generated by fascat\n"]
    if opts.materials and opts.write_mtl and written_materials:
        chunks.append(f"mtllib {output_path.with_suffix('.mtl').name}\n")
    vertex_offset = 1
    normal_offset = 1
    written_vertices = 0
    written_triangles = 0
    for occurrence in _occurrences(asset):
        part = asset.parts.get(occurrence.part_id)
        if part is None or part.mesh is None:
            continue
        mesh = part.mesh
        name = _obj_name(occurrence.node.name or part.name or part.id)
        if opts.preserve_groups:
            chunks.append(f"g {name}\n")
            chunks.append(f"o {name}\n")
        points = _transform_points(mesh.points, occurrence.world_transform)
        written_vertices += int(points.shape[0])
        written_triangles += mesh.triangle_count
        chunks.append(_format_prefixed_rows("v", points))
        normals = _occurrence_normals(mesh, points, occurrence.world_transform)
        chunks.append(_format_prefixed_rows("vn", normals.values))
        chunks.append(f"{_smoothing_directive(mesh, normals.per_face)}\n")
        chunks.extend(
            _face_chunks(
                part,
                mesh,
                vertex_offset=vertex_offset,
                normal_offset=normal_offset,
                per_face_normals=normals.per_face,
                write_materials=opts.materials,
            )
        )
        vertex_offset += mesh.vertex_count
        normal_offset += normals.values.shape[0]

    output_path.write_text("".join(chunks), encoding="utf-8")
    if opts.materials and opts.write_mtl and written_materials:
        _write_mtl(output_path.with_suffix(".mtl"), written_materials)
    if collect_stats and written_vertices > 0 and written_triangles > 0:
        return {"meshes": 1, "points": written_vertices, "triangles": written_triangles}
    return None


def validate_obj(path: str | Path) -> dict[str, int]:
    text = Path(path).read_text(encoding="utf-8")
    vertices = sum(1 for line in text.splitlines() if line.startswith("v "))
    triangles = sum(1 for line in text.splitlines() if line.startswith("f "))
    if vertices == 0 or triangles == 0:
        raise RuntimeError("OBJ asset contains no mesh faces")
    return {"meshes": 1, "points": vertices, "triangles": triangles}


class _Occurrence:
    def __init__(self, node: Node, part_id: str, world_transform: np.ndarray) -> None:
        self.node = node
        self.part_id = part_id
        self.world_transform = world_transform


def _occurrences(asset: Asset) -> list[_Occurrence]:
    occurrences: list[_Occurrence] = []

    def walk(node: Node, world: np.ndarray) -> None:
        current = world @ node.transform
        if node.part_id is not None:
            occurrences.append(_Occurrence(node, node.part_id, current))
        for child in node.children:
            walk(child, current)

    walk(asset.root, np.eye(4, dtype=np.float64))
    return occurrences


def _transform_points(points: np.ndarray, transform: np.ndarray) -> np.ndarray:
    homogeneous = np.column_stack([points, np.ones(points.shape[0], dtype=np.float64)])
    return np.asarray((transform @ homogeneous.T).T[:, :3], dtype=np.float64)


class _ObjNormals:
    def __init__(self, values: np.ndarray, *, per_face: bool) -> None:
        self.values = values
        self.per_face = per_face


def _occurrence_normals(mesh: Mesh, points: np.ndarray, transform: np.ndarray) -> _ObjNormals:
    if mesh.normals is not None:
        return _ObjNormals(_transform_normals(mesh.normals, transform), per_face=False)
    return _ObjNormals(_face_normals(points, mesh.faces), per_face=True)


def _transform_normals(normals: np.ndarray, transform: np.ndarray) -> np.ndarray:
    linear = np.asarray(transform[:3, :3], dtype=np.float64)
    try:
        normal_matrix = np.linalg.inv(linear).T
    except np.linalg.LinAlgError:
        normal_matrix = linear
    return _normalize_rows(normals @ normal_matrix.T)


def _face_normals(points: np.ndarray, faces: np.ndarray) -> np.ndarray:
    if faces.size == 0:
        return np.empty((0, 3), dtype=np.float64)
    triangles = points[faces]
    normals = np.cross(triangles[:, 1] - triangles[:, 0], triangles[:, 2] - triangles[:, 0])
    return _normalize_rows(normals)


def _normalize_rows(values: np.ndarray) -> np.ndarray:
    lengths = np.linalg.norm(values, axis=1)
    result = np.zeros_like(values, dtype=np.float64)
    nonzero = lengths > 0.0
    result[nonzero] = values[nonzero] / lengths[nonzero, None]
    result[~nonzero] = np.array([0.0, 0.0, 1.0], dtype=np.float64)
    return result


def _smoothing_directive(mesh: Mesh, per_face_normals: bool) -> str:
    normal_mode = str(mesh.metadata.get("normal_mode", "")).lower()
    if per_face_normals or normal_mode in {"flat", "hard_edges"}:
        return "s off"
    return "s 1"


def _format_prefixed_rows(prefix: str, values: np.ndarray) -> str:
    if values.shape[0] == 0:
        return ""
    output = StringIO()
    np.savetxt(output, values, fmt=f"{prefix} %.9g %.9g %.9g")
    return output.getvalue()


def _face_chunks(
    part: Part,
    mesh: Mesh,
    *,
    vertex_offset: int,
    normal_offset: int,
    per_face_normals: bool,
    write_materials: bool,
) -> list[str]:
    if mesh.triangle_count == 0:
        return []
    if not write_materials:
        return [
            _face_lines(
                mesh.faces,
                face_start=0,
                vertex_offset=vertex_offset,
                normal_offset=normal_offset,
                per_face_normals=per_face_normals,
            )
        ]

    chunks: list[str] = []
    material_ids = [_face_material_id(part, mesh, face_index) for face_index in range(mesh.triangle_count)]
    start = 0
    while start < mesh.triangle_count:
        material_id = material_ids[start]
        end = start + 1
        while end < mesh.triangle_count and material_ids[end] == material_id:
            end += 1
        if material_id is not None:
            chunks.append(f"usemtl {_obj_name(material_id)}\n")
        chunks.append(
            _face_lines(
                mesh.faces[start:end],
                face_start=start,
                vertex_offset=vertex_offset,
                normal_offset=normal_offset,
                per_face_normals=per_face_normals,
            )
        )
        start = end
    return chunks


def _face_lines(
    faces: np.ndarray,
    *,
    face_start: int,
    vertex_offset: int,
    normal_offset: int,
    per_face_normals: bool,
) -> str:
    vertices = faces.astype(np.int64, copy=False) + vertex_offset
    if per_face_normals:
        normals = np.repeat(
            (np.arange(face_start, face_start + faces.shape[0], dtype=np.int64) + normal_offset)[:, None],
            3,
            axis=1,
        )
    else:
        normals = faces.astype(np.int64, copy=False) + normal_offset
    refs = np.column_stack(
        [
            vertices[:, 0],
            normals[:, 0],
            vertices[:, 1],
            normals[:, 1],
            vertices[:, 2],
            normals[:, 2],
        ]
    )
    output = StringIO()
    np.savetxt(output, refs, fmt="f %d//%d %d//%d %d//%d")
    return output.getvalue()


def _face_material_id(part: Part, mesh: Mesh, face_index: int) -> str | None:
    if not part.material_ids:
        return None
    if mesh.material_indices is None:
        return part.material_ids[0]
    material_index = int(mesh.material_indices[face_index])
    return part.material_ids[material_index] if material_index < len(part.material_ids) else None


def _write_mtl(path: Path, materials: dict[str, Material]) -> None:
    lines: list[str] = ["# Generated by fascat"]
    for material in materials.values():
        lines.append(f"newmtl {_obj_name(material.id)}")
        lines.append(f"Kd {material.base_color[0]:.9g} {material.base_color[1]:.9g} {material.base_color[2]:.9g}")
        lines.append(f"d {material.opacity:.9g}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _obj_name(value: str) -> str:
    return "".join(character if character.isalnum() or character in {"_", "-", "."} else "_" for character in value)
