from __future__ import annotations

import struct
from io import StringIO
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from fascat.asset import Asset, Node
from fascat.options import StlExportOptions

STL_SUFFIXES = {".stl"}
FloatArray = NDArray[np.float64]


def write_stl(asset: Asset, path: str | Path, *, options: StlExportOptions | None = None) -> None:
    _write_stl(asset, path, options=options, collect_stats=False)


def write_stl_with_validation_stats(
    asset: Asset,
    path: str | Path,
    *,
    options: StlExportOptions | None = None,
) -> dict[str, int] | None:
    return _write_stl(asset, path, options=options, collect_stats=True)


def _write_stl(
    asset: Asset,
    path: str | Path,
    *,
    options: StlExportOptions | None,
    collect_stats: bool,
) -> dict[str, int] | None:
    opts = options or StlExportOptions()
    output_path = Path(path)
    if output_path.suffix.lower() not in STL_SUFFIXES:
        raise ValueError(f"unsupported STL extension: {output_path.suffix or '<none>'}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    triangles = _triangles(asset)
    if opts.binary:
        output_path.write_bytes(_binary_stl(triangles))
    else:
        output_path.write_text(_ascii_stl(triangles), encoding="utf-8")
    triangle_count = int(triangles.shape[0])
    if collect_stats and (triangle_count > 0 or opts.binary):
        return {"meshes": 1, "points": triangle_count * 3, "triangles": triangle_count}
    return None


def validate_stl(path: str | Path) -> dict[str, int]:
    payload = Path(path).read_bytes()
    if len(payload) >= 84:
        triangle_count = struct.unpack_from("<I", payload, 80)[0]
        expected = 84 + triangle_count * 50
        if expected == len(payload):
            return {"meshes": 1, "points": triangle_count * 3, "triangles": triangle_count}
    text = payload.decode("utf-8", errors="ignore")
    triangle_count = sum(1 for line in text.splitlines() if line.strip().startswith("facet normal"))
    if triangle_count == 0:
        raise RuntimeError("STL asset contains no triangles")
    return {"meshes": 1, "points": triangle_count * 3, "triangles": triangle_count}


def _triangles(asset: Asset) -> FloatArray:
    chunks: list[FloatArray] = []

    def walk(node: Node, world: FloatArray) -> None:
        current = world @ node.transform
        if node.part_id is not None and node.part_id in asset.parts:
            mesh = asset.parts[node.part_id].mesh
            if mesh is not None:
                points = _transform_points(mesh.points, current)
                chunks.append(points[mesh.faces].astype(np.float64))
        for child in node.children:
            walk(child, current)

    walk(asset.root, np.eye(4, dtype=np.float64))
    if not chunks:
        return np.empty((0, 3, 3), dtype=np.float64)
    return np.concatenate(chunks, axis=0)


def _binary_stl(triangles: FloatArray) -> bytes:
    data = bytearray(b"Generated by fascat".ljust(80, b"\x00"))
    data.extend(struct.pack("<I", triangles.shape[0]))
    records = np.zeros(
        triangles.shape[0],
        dtype=[("normal", "<f4", (3,)), ("vertices", "<f4", (3, 3)), ("attribute", "<u2")],
    )
    records["normal"] = _normals(triangles).astype(np.float32, copy=False)
    records["vertices"] = triangles.astype(np.float32, copy=False)
    data.extend(records.tobytes())
    return bytes(data)


def _ascii_stl(triangles: FloatArray) -> str:
    if triangles.shape[0] == 0:
        return "solid fascat\nendsolid fascat\n"
    rows = np.column_stack([_normals(triangles), triangles.reshape((triangles.shape[0], 9))])
    output = StringIO()
    output.write("solid fascat\n")
    np.savetxt(
        output,
        rows,
        fmt=(
            "  facet normal %.9g %.9g %.9g\n"
            "    outer loop\n"
            "      vertex %.9g %.9g %.9g\n"
            "      vertex %.9g %.9g %.9g\n"
            "      vertex %.9g %.9g %.9g\n"
            "    endloop\n"
            "  endfacet"
        ),
    )
    output.write("endsolid fascat\n")
    return output.getvalue()


def _normals(triangles: FloatArray) -> FloatArray:
    if triangles.shape[0] == 0:
        return np.empty((0, 3), dtype=np.float64)
    normals = np.cross(triangles[:, 1] - triangles[:, 0], triangles[:, 2] - triangles[:, 0])
    lengths = np.linalg.norm(normals, axis=1)
    valid = lengths > 0.0
    result = np.zeros_like(normals, dtype=np.float64)
    result[valid] = normals[valid] / lengths[valid, None]
    return result


def _transform_points(points: FloatArray, transform: FloatArray) -> FloatArray:
    homogeneous = np.column_stack([points, np.ones(points.shape[0], dtype=np.float64)])
    return np.asarray((transform @ homogeneous.T).T[:, :3], dtype=np.float64)
