from __future__ import annotations

import struct
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from fascat.asset import Asset, Node
from fascat.options import StlExportOptions

STL_SUFFIXES = {".stl"}
FloatArray = NDArray[np.float64]


def write_stl(asset: Asset, path: str | Path, *, options: StlExportOptions | None = None) -> None:
    opts = options or StlExportOptions()
    output_path = Path(path)
    if output_path.suffix.lower() not in STL_SUFFIXES:
        raise ValueError(f"unsupported STL extension: {output_path.suffix or '<none>'}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    triangles = _triangles(asset)
    if opts.binary:
        output_path.write_bytes(_binary_stl(triangles))
        return
    output_path.write_text(_ascii_stl(triangles), encoding="utf-8")


def validate_stl(path: str | Path) -> dict[str, int]:
    payload = Path(path).read_bytes()
    if len(payload) >= 84:
        triangle_count = struct.unpack_from("<I", payload, 80)[0]
        expected = 84 + triangle_count * 50
        if expected == len(payload):
            return {"meshes": 1, "points": triangle_count * 3, "triangles": triangle_count}
    text = payload.decode("utf-8", errors="ignore")
    triangle_count = sum(1 for line in text.splitlines() if line.strip().startswith("facet normal"))
    if triangle_count == 0:
        raise RuntimeError("STL asset contains no triangles")
    return {"meshes": 1, "points": triangle_count * 3, "triangles": triangle_count}


def _triangles(asset: Asset) -> list[FloatArray]:
    result: list[FloatArray] = []

    def walk(node: Node, world: FloatArray) -> None:
        current = world @ node.transform
        if node.part_id is not None and node.part_id in asset.parts:
            mesh = asset.parts[node.part_id].mesh
            if mesh is not None:
                points = _transform_points(mesh.points, current)
                result.extend(points[mesh.faces].astype(np.float64))
        for child in node.children:
            walk(child, current)

    walk(asset.root, np.eye(4, dtype=np.float64))
    return result


def _binary_stl(triangles: list[FloatArray]) -> bytes:
    data = bytearray(b"Generated by fascat".ljust(80, b"\x00"))
    data.extend(struct.pack("<I", len(triangles)))
    for triangle in triangles:
        normal = _normal(triangle)
        data.extend(struct.pack("<3f", *normal.astype(np.float32).tolist()))
        for point in triangle:
            data.extend(struct.pack("<3f", *point.astype(np.float32).tolist()))
        data.extend(struct.pack("<H", 0))
    return bytes(data)


def _ascii_stl(triangles: list[FloatArray]) -> str:
    lines = ["solid fascat"]
    for triangle in triangles:
        normal = _normal(triangle)
        lines.append(f"  facet normal {normal[0]:.9g} {normal[1]:.9g} {normal[2]:.9g}")
        lines.append("    outer loop")
        for point in triangle:
            lines.append(f"      vertex {point[0]:.9g} {point[1]:.9g} {point[2]:.9g}")
        lines.append("    endloop")
        lines.append("  endfacet")
    lines.append("endsolid fascat")
    return "\n".join(lines) + "\n"


def _normal(triangle: FloatArray) -> FloatArray:
    normal = np.cross(triangle[1] - triangle[0], triangle[2] - triangle[0])
    length = float(np.linalg.norm(normal))
    if length == 0.0:
        return np.zeros(3, dtype=np.float64)
    return np.asarray(normal / length, dtype=np.float64)


def _transform_points(points: FloatArray, transform: FloatArray) -> FloatArray:
    homogeneous = np.column_stack([points, np.ones(points.shape[0], dtype=np.float64)])
    return np.asarray((transform @ homogeneous.T).T[:, :3], dtype=np.float64)
