"""Convert CAD data into realtime-ready OpenUSD, glTF, OBJ, STL, and FBX assets."""

from fascat import profiles
from fascat.analysis import AnalysisReport
from fascat.asset import Asset, Node, Part
from fascat.filter import Filter, FilterExpressionError, SelectionMatch, SelectionResult
from fascat.image import ImageResource
from fascat.io.brep import read_brep
from fascat.io.fbx import validate_fbx
from fascat.io.gltf import validate_gltf
from fascat.io.iges import read_iges
from fascat.io.step import read_step, read_step_many
from fascat.io.usd import validate_usd
from fascat.material import Material
from fascat.mesh import Mesh, MeshValidationError
from fascat.metadata import Metadata, PmiAnnotation, Tolerance
from fascat.options import (
    AabbProjectionOptions,
    AnalyzeOptions,
    AtlasOptions,
    BakeMaterialOptions,
    BrepHealOptions,
    BrepReadOptions,
    DecimateOptions,
    DeleteDegeneratePolygonsOptions,
    ExplodeOptions,
    FbxExportOptions,
    GltfExportOptions,
    IgesReadOptions,
    LODGeneratorOptions,
    LODLevel,
    LODOptions,
    MergeOptions,
    MergeVerticesOptions,
    MetadataExportOptions,
    ObjExportOptions,
    OptimizeOptions,
    PlatformBudget,
    RemoveHolesOptions,
    RemoveOccludedOptions,
    RepairOptions,
    ReplaceOptions,
    SceneOptimizeOptions,
    StageOptions,
    StepReadOptions,
    StlExportOptions,
    TessellationOptions,
    TextureProcessOptions,
    UnwrapOptions,
    UsdExportOptions,
    WorkflowRecipe,
    WorkflowRecipeChoice,
    gltf_export_preset_texture_options,
    resolve_gltf_export_options,
)
from fascat.pipeline import (
    analyze,
    bake_materials,
    convert,
    decimate,
    delete_degenerate_polygons,
    explode,
    heal_brep,
    lods,
    merge,
    merge_vertices,
    optimize,
    optimize_scene,
    process_textures,
    remove_holes,
    remove_occluded,
    repair,
    replace,
    run_lod_generators,
    stage,
    tessellate,
    validate_output,
    write_fbx,
    write_gltf,
    write_obj,
    write_stl,
    write_usd,
)
from fascat.pipeline_file import PipelineSpec, PipelineStep
from fascat.runtime import (
    RuntimeBrowserOptions,
    RuntimeBrowserRenderOptions,
    RuntimeBrowserRenderReport,
    RuntimeBrowserReport,
    RuntimeEngineOptions,
    RuntimeEngineReport,
    copy_engine_runtime_harness,
    measure_browser_runtime,
    measure_engine_runtime,
    write_browser_render_preview,
)
from fascat.runtime_fixtures import (
    RuntimeParityCapture,
    RuntimeParityCaptureReport,
    RuntimeParityFixture,
    RuntimeParityGolden,
    RuntimeParityGoldenCoverageReport,
    RuntimeParitySuiteReport,
    audit_runtime_parity_goldens,
    capture_runtime_parity_suite,
    write_runtime_parity_suite,
)
from fascat.size_ladder import GltfSizeLadderReport, GltfSizeLadderVariant, measure_gltf_size_ladder
from fascat.visual import (
    LodSwitchPreviewReport,
    VisualComparisonReport,
    VisualDiffOptions,
    VisualDiffReport,
    VisualPreviewOptions,
    VisualPreviewReport,
    compare_images,
    write_before_after_previews,
    write_lod_switch_previews,
    write_output_lod_switch_previews,
    write_output_preview,
    write_preview,
)

__version__ = "0.2.0"

__all__ = [
    "Asset",
    "AabbProjectionOptions",
    "AnalysisReport",
    "AnalyzeOptions",
    "AtlasOptions",
    "BakeMaterialOptions",
    "BrepHealOptions",
    "BrepReadOptions",
    "DecimateOptions",
    "DeleteDegeneratePolygonsOptions",
    "ExplodeOptions",
    "FbxExportOptions",
    "Filter",
    "FilterExpressionError",
    "GltfExportOptions",
    "GltfSizeLadderReport",
    "GltfSizeLadderVariant",
    "IgesReadOptions",
    "ImageResource",
    "LODGeneratorOptions",
    "LODLevel",
    "LODOptions",
    "Material",
    "Metadata",
    "MetadataExportOptions",
    "MergeOptions",
    "MergeVerticesOptions",
    "Mesh",
    "MeshValidationError",
    "Node",
    "ObjExportOptions",
    "OptimizeOptions",
    "PlatformBudget",
    "Part",
    "PmiAnnotation",
    "PipelineSpec",
    "PipelineStep",
    "RepairOptions",
    "RemoveHolesOptions",
    "RemoveOccludedOptions",
    "RuntimeBrowserOptions",
    "RuntimeBrowserRenderOptions",
    "RuntimeBrowserRenderReport",
    "RuntimeBrowserReport",
    "RuntimeEngineOptions",
    "RuntimeEngineReport",
    "RuntimeParityCapture",
    "RuntimeParityCaptureReport",
    "RuntimeParityFixture",
    "RuntimeParityGolden",
    "RuntimeParityGoldenCoverageReport",
    "RuntimeParitySuiteReport",
    "SceneOptimizeOptions",
    "ReplaceOptions",
    "SelectionMatch",
    "SelectionResult",
    "StageOptions",
    "StepReadOptions",
    "StlExportOptions",
    "TessellationOptions",
    "TextureProcessOptions",
    "Tolerance",
    "UnwrapOptions",
    "UsdExportOptions",
    "LodSwitchPreviewReport",
    "VisualComparisonReport",
    "VisualDiffOptions",
    "VisualDiffReport",
    "VisualPreviewOptions",
    "VisualPreviewReport",
    "WorkflowRecipe",
    "WorkflowRecipeChoice",
    "__version__",
    "analyze",
    "bake_materials",
    "compare_images",
    "convert",
    "copy_engine_runtime_harness",
    "audit_runtime_parity_goldens",
    "capture_runtime_parity_suite",
    "decimate",
    "delete_degenerate_polygons",
    "explode",
    "heal_brep",
    "lods",
    "merge",
    "merge_vertices",
    "measure_gltf_size_ladder",
    "measure_browser_runtime",
    "measure_engine_runtime",
    "optimize",
    "optimize_scene",
    "process_textures",
    "profiles",
    "read_step",
    "read_step_many",
    "read_brep",
    "read_iges",
    "repair",
    "remove_holes",
    "remove_occluded",
    "replace",
    "resolve_gltf_export_options",
    "run_lod_generators",
    "stage",
    "tessellate",
    "validate_gltf",
    "validate_fbx",
    "validate_output",
    "validate_usd",
    "write_gltf",
    "write_runtime_parity_suite",
    "write_obj",
    "write_stl",
    "write_fbx",
    "write_usd",
    "write_before_after_previews",
    "write_browser_render_preview",
    "write_lod_switch_previews",
    "write_output_lod_switch_previews",
    "write_output_preview",
    "write_preview",
    "gltf_export_preset_texture_options",
]
