"""Convert CAD STEP data into realtime-ready OpenUSD and glTF assets."""

from fascat import profiles
from fascat.analysis import AnalysisReport
from fascat.asset import Asset, Node, Part
from fascat.filter import Filter, FilterExpressionError, SelectionMatch, SelectionResult
from fascat.io.gltf import validate_gltf
from fascat.io.step import read_step
from fascat.io.usd import validate_usd
from fascat.material import Material
from fascat.mesh import Mesh, MeshValidationError
from fascat.metadata import Metadata, PmiAnnotation, Tolerance
from fascat.options import (
    AnalyzeOptions,
    AtlasOptions,
    BakeMaterialOptions,
    BrepHealOptions,
    DecimateOptions,
    ExplodeOptions,
    GltfExportOptions,
    LODGeneratorOptions,
    LODLevel,
    LODOptions,
    MergeOptions,
    MetadataExportOptions,
    ObjExportOptions,
    OptimizeOptions,
    RemoveHolesOptions,
    RemoveOccludedOptions,
    RepairOptions,
    ReplaceOptions,
    SceneOptimizeOptions,
    StageOptions,
    StepReadOptions,
    StlExportOptions,
    Tessellation,
    UnwrapOptions,
    UsdExportOptions,
)
from fascat.pipeline import (
    analyze,
    bake_materials,
    convert,
    decimate,
    explode,
    heal_brep,
    lods,
    merge,
    optimize,
    optimize_scene,
    remove_holes,
    remove_occluded,
    repair,
    replace,
    run_lod_generators,
    stage,
    tessellate,
    validate_output,
    write_gltf,
    write_obj,
    write_stl,
    write_usd,
)
from fascat.pipeline_file import PipelineSpec, PipelineStep

__version__ = "0.1.0"

__all__ = [
    "Asset",
    "AnalysisReport",
    "AnalyzeOptions",
    "AtlasOptions",
    "BakeMaterialOptions",
    "BrepHealOptions",
    "DecimateOptions",
    "ExplodeOptions",
    "Filter",
    "FilterExpressionError",
    "GltfExportOptions",
    "LODGeneratorOptions",
    "LODLevel",
    "LODOptions",
    "Material",
    "Metadata",
    "MetadataExportOptions",
    "MergeOptions",
    "Mesh",
    "MeshValidationError",
    "Node",
    "ObjExportOptions",
    "OptimizeOptions",
    "Part",
    "PmiAnnotation",
    "PipelineSpec",
    "PipelineStep",
    "RepairOptions",
    "RemoveHolesOptions",
    "RemoveOccludedOptions",
    "SceneOptimizeOptions",
    "ReplaceOptions",
    "SelectionMatch",
    "SelectionResult",
    "StageOptions",
    "StepReadOptions",
    "StlExportOptions",
    "Tessellation",
    "Tolerance",
    "UnwrapOptions",
    "UsdExportOptions",
    "__version__",
    "analyze",
    "bake_materials",
    "convert",
    "decimate",
    "explode",
    "heal_brep",
    "lods",
    "merge",
    "optimize",
    "optimize_scene",
    "profiles",
    "read_step",
    "repair",
    "remove_holes",
    "remove_occluded",
    "replace",
    "run_lod_generators",
    "stage",
    "tessellate",
    "validate_gltf",
    "validate_output",
    "validate_usd",
    "write_gltf",
    "write_obj",
    "write_stl",
    "write_usd",
]
